# Maybe...

# Currently v3 is really messy (Vibe Coded). So I'm going to recode it if all goes wrong in v3. Meaning, v1 will 
# actually be deprecated and replaced with a v4-lite later down the line. V3 will also be deprecated...